/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#ecfdf5',
                    100: '#d1fae5',
                    200: '#a7f3d0',
                    300: '#6ee7b7',
                    400: '#34d399',
                    500: '#10b981',
                    600: '#059669',
                    700: '#047857',
                    800: '#065f46',
                    900: '#064e3b',
                },
                secondary: {
                    50: '#fffbeb',
                    100: '#fef3c7',
                    200: '#fde68a',
                    300: '#fcd34d',
                    400: '#fbbf24',
                    500: '#f59e0b',
                    600: '#d97706',
                    700: '#b45309',
                    800: '#92400e',
                    900: '#78350f',
                },
                danger: {
                    50: '#fef2f2',
                    100: '#fee2e2',
                    200: '#fecaca',
                    300: '#fca5a5',
                    400: '#f87171',
                    500: '#ef4444',
                    600: '#dc2626',
                    700: '#b91c1c',
                    800: '#991b1b',
                    900: '#7f1d1d',
                },
                info: {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    800: '#1e40af',
                    900: '#1e3a8a',
                },
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
            },
            boxShadow: {
                'soft': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                'soft-lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
            },
        },
    },
    plugins: [
        function ({ addComponents }) {
            addComponents({
                '.badge-warning': {
                    backgroundColor: '#fef3c7',
                    color: '#92400e',
                    padding: '0.25rem 0.5rem',
                    borderRadius: '0.25rem',
                    fontSize: '0.75rem',
                    fontWeight: '500',
                },
                '.badge-success': {
                    backgroundColor: '#d1fae5',
                    color: '#065f46',
                    padding: '0.25rem 0.5rem',
                    borderRadius: '0.25rem',
                    fontSize: '0.75rem',
                    fontWeight: '500',
                },
                '.badge-danger': {
                    backgroundColor: '#fee2e2',
                    color: '#991b1b',
                    padding: '0.25rem 0.5rem',
                    borderRadius: '0.25rem',
                    fontSize: '0.75rem',
                    fontWeight: '500',
                },
                '.badge-info': {
                    backgroundColor: '#dbeafe',
                    color: '#1e40af',
                    padding: '0.25rem 0.5rem',
                    borderRadius: '0.25rem',
                    fontSize: '0.75rem',
                    fontWeight: '500',
                },
                '.badge-secondary': {
                    backgroundColor: '#f3e8ff',
                    color: '#6b21a8',
                    padding: '0.25rem 0.5rem',
                    borderRadius: '0.25rem',
                    fontSize: '0.75rem',
                    fontWeight: '500',
                },
                '.badge-gray': {
                    backgroundColor: '#f3f4f6',
                    color: '#374151',
                    padding: '0.25rem 0.5rem',
                    borderRadius: '0.25rem',
                    fontSize: '0.75rem',
                    fontWeight: '500',
                },
                '.btn-primary': {
                    backgroundColor: '#10b981',
                    color: 'white',
                    padding: '0.5rem 1rem',
                    borderRadius: '0.5rem',
                    transition: 'background-color 0.2s',
                    fontWeight: '500',
                },
                '.btn-primary:hover': {
                    backgroundColor: '#059669',
                },
                '.btn-gray': {
                    backgroundColor: '#6b7280',
                    color: 'white',
                    padding: '0.5rem 1rem',
                    borderRadius: '0.5rem',
                    transition: 'background-color 0.2s',
                    fontWeight: '500',
                },
                '.btn-gray:hover': {
                    backgroundColor: '#4b5563',
                },
                '.btn-danger': {
                    backgroundColor: '#ef4444',
                    color: 'white',
                    padding: '0.5rem 1rem',
                    borderRadius: '0.5rem',
                    transition: 'background-color 0.2s',
                    fontWeight: '500',
                },
                '.btn-danger:hover': {
                    backgroundColor: '#dc2626',
                },
                '.card': {
                    backgroundColor: 'white',
                    borderRadius: '0.75rem',
                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                    padding: '1rem',
                },
                '.card-secondary': {
                    backgroundColor: '#fffbeb',
                    borderRadius: '0.75rem',
                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                    padding: '1rem',
                    border: '1px solid #fde68a',
                },
                '.card-info': {
                    backgroundColor: '#eff6ff',
                    borderRadius: '0.75rem',
                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                    padding: '1rem',
                    border: '1px solid #bfdbfe',
                },
                '.card-success': {
                    backgroundColor: '#ecfdf5',
                    borderRadius: '0.75rem',
                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                    padding: '1rem',
                    border: '1px solid #a7f3d0',
                },
                '.card-danger': {
                    backgroundColor: '#fef2f2',
                    borderRadius: '0.75rem',
                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                    padding: '1rem',
                    border: '1px solid #fecaca',
                },
                '.shadow-soft': {
                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                },
                '.header-primary': {
                    backgroundImage: 'linear-gradient(to right, #059669, #064e3b)',
                    color: 'white',
                    padding: '1rem',
                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                    position: 'sticky',
                    top: '0',
                    zIndex: '10',
                },
                '.alert-success': {
                    backgroundColor: '#d1fae5',
                    borderLeft: '4px solid #10b981',
                    color: '#065f46',
                    padding: '1rem',
                    borderRadius: '0.5rem',
                    marginBottom: '1rem',
                },
                '.alert-danger': {
                    backgroundColor: '#fee2e2',
                    borderLeft: '4px solid #ef4444',
                    color: '#991b1b',
                    padding: '1rem',
                    borderRadius: '0.5rem',
                    marginBottom: '1rem',
                },
                '.alert-info': {
                    backgroundColor: '#dbeafe',
                    borderLeft: '4px solid #3b82f6',
                    color: '#1e40af',
                    padding: '1rem',
                    borderRadius: '0.5rem',
                    marginBottom: '1rem',
                },
                '.alert-warning': {
                    backgroundColor: '#fef3c7',
                    borderLeft: '4px solid #f59e0b',
                    color: '#92400e',
                    padding: '1rem',
                    borderRadius: '0.5rem',
                    marginBottom: '1rem',
                },
            });
        },
    ],
};
